# Generated by Django 3.2.1 on 2021-05-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210527_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=64, null=True, unique=True, verbose_name='이메일'),
        ),
    ]
