# Generated by Django 3.2.1 on 2021-05-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210527_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth',
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('2', 'Lv2_인증사용자'), ('1', 'Lv1_관리자'), ('0', 'Lv0_개발자')], default=3, max_length=18, verbose_name='등급'),
        ),
    ]
